=== Data

==== Background

While interoperability at the metadata level is important for SDMS,
exchange of observations and data products is vital to the success of
SDMS. This implies both exchange of archived data as well as exchange of
real time information. In order to facilitate such exchange of
information within the SDMS community a certain level of standardisation
is required, especially in order to be able to automatically combine
multiple datasets into a new dataset fulfilling user requirements (e.g.
for CalVal activities). This standardisation is also required to ensure
that all users can easily understand the data that is made available and
perform intercomparisons as well as use it in analyses.

In this context documentation of data through standardised use metadata
is required. By use metadata is understood identification of the
variables, their structure (e.g. spatiotemporal dimensions and mapping
to file format), units of variables, encoding of missing values,
quality/accuracy estimates, map projection and coordinate reference
system etc.

Application of a common data model simplifies integration and
intercomparison of datasets. Application of NetCDFlink:#anchor-17[[19] ]
as the file format, utilising the Climate and
Forecastlink:#anchor-18[[20] ] convention and serving data through
OPeNDAPlink:#anchor-19[[21] ] simplifies the issue of integration and
combination of data through the Common Data Modellink:#anchor-20[[22] ].
Other solutions may be added, but this is an easy win and address
requirements both within numerical simulation communities, satellite
CalVal communities and WMO programmes.

1.  Where possible, OPeNDAP should be supported for data access
(combining multiple physical files to a single virtual dataset).

Several OPeNDAP implementations exist (e.g.
http://www.unidata.ucar.edu/software/thredds/current/tds/[THREDDS],
https://coastwatch.pfeg.noaa.gov/erddap/index.html[ERDDAP],
http://docs.opendap.org/index.php/Hyrax[Hyrax] and
http://www.pydap.org/[pyDAP]). pyDAP can integrate with relational
databases. Utilisation of OPeNDAP simplifies handling of both archive
and real time data as the real time segmentation of data is performed by
the client asking for data. _OPeNDAP also minimises the overhead as no
files are moved, the client connects to data streams, reads the
necessary data and close the connection._

include::sdms_iog_ch02-data-protocols.adoc[]

include::sdms_iog_ch02-data-formats.adoc[]
