[[discovery-metadata]]
=== Discovery metadata

==== Background

Metadata are generated by the data centres hosting the data sets.
Metadata are harvested and ingested in the central catalogue for usage
by the SIOS Data Portal user community. SIOS Data Portal metadata are
divided in 4 categories:

1.  Index metadata for identifying relevant products for a specific
purpose.
2.  Configuration metadata for tuning of user services for a specific
data set.
3.  Use metadata for understanding the data accessed.
4.  Site metadata for understanding the context in which a dataset has
been generated.

The first category is the metadata provided by the data centres in a
standard format, e.g. GCMD DIF or ISO 19115. The second category is
maintained in the central metadata repository and is used for
configuration of higher order services like visualisation,
transformation, etc., and is created internally in the SIOS Data Portal
based on information retrieved from contributing data centres. The third
category is covered e.g. by utilisation of NetCDF files formatted
according to the Climate and Forecast Convention where sufficient
information to actually use the data is provided. The fourth category
links directly to WIGOS metadatafootnote:[WIGOS Metadata are based on
the OGC Observations and Measurements Schema.]. These metadata describes
the station, its surroundings, instrumentation, procedures etc. There is
some overlap between these metadata and the first category.

The SIOS Data Portal harvest metadata to a central repository that is
used to search for relevant datasets. It does not utilise distributed
search as this is a slower process compared to searching in a central
repository. Metadata are harvested at regular intervals and checked for
conformance according to the standards identified herein and in
link:#anchor-7[[8] ].

Regardless of the metadata standard used and the mechanism for transport
of the information the following recommendation should be implemented at
the repositories.

1.  [[anchor-26]]All datasets should have a unique identifier issued by
the host data centre. This is used to track datasets in the central
repository and check for duplicates. The identifier is set by the
authoritative source for the dataset.
2.  link:#anchor-26[REC. 1.] implies that SIOS Data Portal will not
specify or change a unique identifier unless the dataset is hosted by
the SIOS Data Portal.

==== Exchange mechanisms for metadata

===== Introduction

Metadata should be exposed using a suitable interface that allows
information on existing datasets as well as changes to the inventory to
be conveyed to the SIOS Data Portal. Suitable interfaces for this are
OAI-PMH and OGC CSWfootnote:[Not fully tested yet.]. Other interfaces
may be evaluated, but to ensure a cost effective solution the number
interfaces must be limited.

OAI-PMH is the recommended interface to use due to its simplicity and
cost effective nature. A number of software solutions supporting this is
freely available.

===== OAI-PMH

The Open Archives Initiatives Protocol for Metadata Harvesting (OAI-PMH)
is the recommended interface for providing discovery metadata to the
SIOS Data Portal. It is a cost effective and robust implementation for
exchange of metadata between data centres. It is much cheaper to
implement than most alternatives and there are a number of tools
available. Some of these are listed on link:#anchor-11[[13] ]. Some not
listed but worth examining are https://pypi.python.org/pypi/pyoai[pyOAI]
and http://pypi.python.org/pypi/MOAI[MOAI].

When implementing OAI-PMH there is a number of SDMS recommendations that
are based on experience during the International Polar Year and SIOS
Preparatory Phase.

1.  OAI-PMH version 2 must be used.
2.  When implementing OAI-PMH for large repositories containing much
more than SIOS relevant data, configuration of a dedicated SIOS set is
strongly recommended as this reduce the load on the SIOS Data Portal
which otherwise has to do filtering of all harvested metadata. The name
of the set that SDMS should harvest has to be communicated and a set
sepcification like “SIOS” is recommended. More information is available
in http://www.openarchives.org/OAI/openarchivesprotocol.html#Set[OAI-PMH
Set specification].
3.  When records are deleted in the contributing data centres
catalogues, information on this has to be communicated to the central
catalogue. In order to achieve this OAI-PMH identifies the support for
deleted records through the *deletedRecord* element retrieved in the
Identify request. Valid responses are no, persistent and transient. SDMS
contributing data centres must support *transient* and must maintain
transient records for at least 1 monthfootnote:[This may change.]. More
information on this feature is available in
http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords[OAI-PMH
specification of deleted records].
4.  The OAI-PMH interface by default offers metadata in
http://dublincore.org/[Dublin Core]. This is insufficient for SDMS
purposes. Metadata has to be offered in
https://github.com/ISO-TC211/XML[ISO19115] and/or
http://gcmd.nasa.gov/add/difguide/[GCMD DIF]. Details on these
specifications are provided below. In order to properly identify the
metadata standards it is recommended to use the following keywords:
“dif” for GCMD DIF, “iso” for ISO19115 minimum profile.

===== OGC CSW

The Open Geospatial Consortium Catalogue Services for the Web (OGC CSW
link:#anchor-12[[14] ]) is another standard for exposing the content of
a catalogue in a standardised form. Similar to OAI-PMH records are
exposed using XML. Compared to OAI-PMH, OGC CSW is more expensive to
implement from the specification although there are several tools
supporting it. It is the recommended exchange mechanism for metadata
within the European framework INSPIREfootnote:[Not required for
scientific data.] and will be supported by the SIOS Data Portal although
OAI-PMH is recommended from a cost benefit perspective for partners not
having this functionality already implemented.

1.  OGC CSW version 2.0.2 must be used.
2.  It is *not* recommended to embed OGC CSW requests in messaging
frameworks like e.g. SOAP.

Details on how to interact with a OGC CSW interface has to be discussed
when there is a SDMS data centre that wants to use this interface.

===== Sensor Description

The implementation of Sensor Web Enablement (SWE) as a useful suite of
standards of the OGC for building the Sensor Web is recommended to allow
for interoperability and to reduce the integration efforts of new data
sources. Recommended data formats are Observations and Measurements
(O&M) and SensorML. For describing devices and sensors in terms of meta
data to NRT-data streams or archived and disseminated data basic
SensorML should be applicable. These are Standard for modelling/encoding
sensor Metadata based on XML (latest version: SensorML 2.0) with
flexible standards on “Which metadata are necessary for SDMS?” Hence
Editors are needed to facilitate the provision of these metadata to the
SDMS with focus on ISO 19115 metadata. As controlled vocabulary for
device description the NERC-SeaDataNet vocabulary could be a useful
recommendation if agreed on.

===== Other

Other mechanisms like OpenSearch could also potentially be supported in
the future, but is currently not supported. According to
link:#anchor-21[[23] ] OpenSearch is a “collection of simple formats for
the sharing of search results. The OpenSearch description document
format can be used to describe a search engine so that it can be used by
search client applications.”

==== Structures

include::sdms_iog_ch02-discovery-iso19115.adoc[]

include::sdms_iog_ch02-discovery-gcmd.adoc[]

