== Introduction

=== Background

Environmental and climate changes are currently observed at a global scale and in particular in the Arctic. In order to give better estimates of the future changes, the Arctic has to be monitored and analysed by a multi-disciplinary observation system which is suited to validate and gradually improve Earth System Models. The best chance to achieve significant results within a relatively short time frame is found in regions with a large natural climate gradient, and where processes sensitive to the expected changes are particularly important.

Svalbard and the surrounding ocean areas fulfil all these criteria; Svalbard is located in a region with a very large climate gradient, being alternately influenced by cold central Arctic or mild marine climate conditions at time scales of weeks to years. It is also located in the region with the strongest inflow and outflow processes between the Arctic and lower-latitude oceans. In addition, Svalbard is the only region in the world (and has the facilities) where one can study and quantify one of the remaining unknowns in the climate puzzle; the extraterrestrial and especially solar influence on climate.

The vision for the Svalbard Integrated Arctic Earth Observing System (SIOS) is to be a regional observational system for long term acquisition and proliferation of fundamental knowledge on global environmental change within an Earth System Science (ESS) perspective in and around Svalbard. SIOS will systematically develop and implement methods for how observational networks are to be construed and thus become a leading observational system in the Arctic and Polar regions. The SIOS Data Management System (SDMS) [[anchor-2]]https://sios-svalbard.org/metsis/search?f%5B0%5D=dataset_level%3ALevel-1[Data Access Portal] is the entry point to SIOS datasets. It offers a web interface that contains information about datasets (metadata). These metadata are harvested on a regular basis from [[anchor-3]]https://sios-svalbard.org/DataSubmission[data centres contributing to SIOS]. These data centres manage the data on behalf of the owners and providers of the data.

A major innovative element of SIOS will be the Knowledge Centre, which will facilitate interaction between observation, modelling and process research, strategic processes, a service point to user communities and a platform for data handling and utilization <<#anchor-4,[3]>>. The SIOS Data Management System (SDMS) will be a functionality-enabling component of the Knowledge Centre, supporting data submission, discovery, access, use and preservation of SIOS relevant datasets.

For the SDMS the term “dataset” is defined in line with the INSPIRE Directive as “an identifiable collection of spatial data”, i.e. a collection of data that has a reference by name or coordinates to a geographic location or area, as well as designated start and end times. A dataset can contain observations (remote or in situ), derived quantities (from either of these two types of data sources) or forecasts of future states of environmental parameters. The data values can be located at a single point, along a line or transect, in a regular or irregular grid, and be captured or estimated at one or more altitudes/depths. A dataset can be stored on paper, in files (one or more), or in a database, and is often accompanied by descriptions (metadata) of its content. The purpose of the SDMS is to provide the SIOS user community a single entry point to relevant datasets. It is however not the purpose to centralise all data, but rather to integrate existing and future data centres contributing to SIOS using machine readable interfaces to metadata and data.

The first version of this document is based on a similar document
developed for WMO Global Cryosphere Watch.

[[scope]]
=== Scope

This document identifies aspects that have to be handled in establishing
SDMS. The purpose is to enable transparency on metadata and in the long
term also on data through limiting the interfaces to be developed and
maintained. The short term goal is to enable visibility of relevant
datasets through discovery metadata, and in the long term to harmonize
accessing data via a defined set of data access interfaces. Emphasis is
primarily on the semantics and structure of interfaces to metadata and
data, and less on underlying file formats.

The requirements in the document represent long term goals, requiring funding for full implementation. Some partners have implemented parts of the interfaces mentioned, while others have a longer way to go. This is reflected in the prioritised functionality to implement as outlined in the implementation plan of the SIOS Preparatory Phase <<#anchor-4,[3]>>, see section 5.3.1footnote:[The official version of this document has some issues with references, an updated version will be made available within the collaboration area for the SDMS WG. ].

[[intended-audience]]
=== Intended audience

System managers at the data centres contributing to the SDMS.

[[training]]
=== Training and support

SIOS-KC offers help and services related to preparing metadata and data in accordance to the FAIR data management principes (Wilkinson et al., 2016) and the interoperability guidelines outlined within this document. You can find information about training courses, online material, and what support SIOS-KC can offer you [[anchor-6]]https://sios-svalbard.org/DMsupport[here].



[[applicable-documents]]
=== Applicable documents

. [[siosdatapolicy]] https://sios-svalbard.org/sites/sios-svalbard.org/files/common/SIOS_Data_Policy.pdf[SIOS Data Policy]
. SDMS Concepts and acronyms
. SDMS System Requirements Document
. SDMS Architecture Design Document
. SDMS System implementation and integration plan
. [[anchor-7]]SDMS Operations Manual
. [[anchor-8]]https://community.wmo.int/activity-areas/wis[WMO Information System]
. [[anchor-9]]https://community.wmo.int/discovery-metadata[WMO Core Profile of the ISO 19115]
. [[anchor-10]]https://community.wmo.int/activity-areas/wigos[WIGOS]
. http://www.openarchives.org/OAI/openarchivesprotocol.html[The Open Archives Initiative Protocol for Metadata Harvesting, Version 2]
. [[anchor-11]]https://www.openarchives.org/pmh/tools/tools.php[OAI-PMH tools]
. [[anchor-12]]http://www.opengeospatial.org/standards/cat[OGC CSW specification]
. [[anchor-13]]https://www.earthdata.nasa.gov/learn/articles/gcmd-retrospective-and-future[GCMD: Data, Services and Tools guide]
. [[anchor-14]]https://www.earthdata.nasa.gov/learn/find-data/idn/gcmd-keywords[GCMD Science Keywords]
. [[anchor-15]]http://cfconventions.org/standard-names.html[Climate and Forecast Standard Names]
. [[anchor-16]]http://wis.wmo.int/2013/metadata/version_1-3-0/WMO_Core_Metadata_Profile_v1.3_Part_2.pdf[WMO Code Lists]
. [[anchor-17]]http://www.unidata.ucar.edu/software/netcdf/[NetCDF]
. [[anchor-18]]http://cfconventions.org/[Climate and Forecast Conventions]
. [[anchor-19]]http://opendap.org/[OPeNDAP]
. [[anchor-20]]https://www.unidata.ucar.edu/software/netcdf-java/v4.6/CDM/index.html[UNIDATA's Common Data Model]
. [[anchor-21]]http://www.opensearch.org/[OpenSearch]
. [[anchor-22]]Wilkinson et al., 2016: http://www.nature.com/articles/sdata201618[The FAIR Guiding Principles for scientific data management and stewardship]
. [[spdxlist]]https://spdx.org/licenses/[SPDX License List]
. https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv[[#osgeo]#OSGeo Link Properties Lookup Table#]
. [[gcmd]]https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/rucontenttype/?format=csv[GCMD URL Types]
