[appendix]
== Outline for Product Manual

=== Introduction
When datasets cannot be presented in a FAIR compliant file format (i.e. self describing), a product manual describing the dataset and how to interpret it *should* accompany the dataset. This product manual has to be served as a PDF document and have the sections identified below.

=== Outline
Outline of sections that should be covered by a product manual for data that cannot be described in a FAIR compliant file format. 

IMPORTANT: The file formats used should always be free and open, not commercial. 

. Introduction
.. General overview of the data production process
. Description of the data
.. Description of which variables that are measured, their characteristics including units on variables etc.
. Description of the file format
.. Description of structure and organisation of the data within this file format. Should include all necessary information to decode the file.
. References to software
.. Description of and links to software that can read and interpret the data. Should focus on open software. Alternatively code snippets for Python, R etc could be embedded in the document.
