[[discovery-metadata]]
=== Discovery metadata

==== Background

Metadata are generated by the data centres hosting the datasets.  
Metadata are harvested and ingested in the central catalogue for usage by the SIOS Data Access Portal user community. 
SIOS Data Access Portal metadata are divided in 4 categories:

1.  Index metadata for identifying relevant products for a specific purpose.
2.  Configuration metadata for tuning of user services for a specific dataset.
3.  Use metadata for understanding the data accessed.
4.  Site metadata for understanding the context in which a dataset has been generated.

The first category is the metadata provided by the data centres in a standard format, e.g. GCMD DIF or ISO 19115. 
The second category is maintained in the central metadata repository and is used for configuration of higher order services like visualisation, transformation, etc., and is created internally in the SIOS Data Access Portal based on information retrieved from contributing data centres. 
The third category is covered e.g. by utilisation of NetCDF files formatted according to the Climate and Forecast Convention where sufficient information to actually use the data is provided. The fourth category links directly to WIGOS metadata footnote:[WIGOS Metadata are based on the OGC Observations and Measurements Schema.]. 
These metadata describes the station, its surroundings, instrumentation, procedures etc. 
There is some overlap between these metadata and the first category.

The SIOS Data Access Portal harvests metadata to a central repository that is used to search for relevant datasets. 
It does not utilise distributed search as this is a slower process compared to searching in a central repository. 
Metadata are harvested at regular intervals and checked for conformance according to the standards identified herein and in <<RD-7>>. 
The discovery metadata are harvested from partner data repositories every night, then converted to the data model used in the data catalogue and ingested if it passes the quality check. 
The nightly harvest is an incremental harvest of changes since the last time the harvest was run. 
Every 3 months a full harvest is done to clean up potentially stale datasets. 

NOTE: A separate document is developed on the harvest process (release pending conversion from LibreOffice document to ASCIIDOC and addition to GitHub).

Regardless of the metadata standard used and the mechanism for transport of the information the following recommendation should be implemented at the repositories.

[horizontal]
[[anchor-26]]Requirement:: 
All datasets should have a unique identifier issued by the host data centre. This is used to track datasets in the central repository and check for duplicates. The identifier is set by the authoritative source for the dataset.

This implies that SIOS Data Access Portal will not specify or change a unique identifier unless the dataset is hosted by the SIOS Data Access Portal.

NOTE: The only exception to this is when SIOS is harvesting discovery metadata using THREDDS Data Catalogues (described later) and the underlying NetCDF files doesn't have a proper and guaranteed unique identifier.

[horizontal]
Recommendation::
Always include a license in the discovery metadata. Following the xref:siosdatapolicy[SIOS Data Policy], SIOS recommends usage of the Creative Commons Attribution License and use identifiers and URL to license text from https://spdx.org/licenses/. 
It is recommended to include both a standardised identifier and a link to the full license text. 

==== Exchange mechanisms for metadata

===== Introduction

Metadata should be exposed using a suitable interface that allows information on existing datasets as well as changes to the inventory to be conveyed to the SIOS Data Access Portal. 
Suitable interfaces for this are OAI-PMH and OGC CSW. Other interfaces are constantly evaluated, but to ensure a cost effective solution the number interfaces must be limited.

[horizontal]
Recommendation::
OAI-PMH is the recommended interface to use due to its simplicity and cost effective nature. 
A number of software solutions supporting this is freely available.

Although OAI-PMH is recommended, OGC CSW will also be harvested. 
Work is in progress to enable support for other exchange mechanisms for discovery metadata.

===== OAI-PMH

The Open Archives Initiatives Protocol for Metadata Harvesting (OAI-PMH) is the recommended interface for providing discovery metadata to the SIOS Data Access Portal. 
It is a cost-effective and robust implementation for exchange of metadata between data centres. 
It is much cheaper to implement than most alternatives and there are a number of open source tools available that implements this (e.g. pycsw, GeoNetwork).
Some of these are listed on <<RD-14>>. 
The central node of SDMS is using https://pycsw.org/[pyCSW] to provide OAI-PMH (and other machine readable en points).

When implementing OAI-PMH there is a number of SDMS recommendations that are based on experience during the International Polar Year, SIOS Preparatory Phase and the operation of SDMS.

[horizontal]
Requirement::
OAI-PMH version 2 must be used.
Recommendation::
When implementing OAI-PMH for large repositories containing much more than SIOS relevant data, configuration of a dedicated SIOS set is strongly recommended as this reduces the load on the SDMS, which otherwise has to do filtering of all harvested metadata. 
The name of the set that SDMS should harvest has to be communicated, and a set specification like “SIOS” is recommended. 
More information is available in http://www.openarchives.org/OAI/openarchivesprotocol.html#Set[OAI-PMH Set specification].
Recommendation::
When records are deleted in the contributing data centres catalogues, information on this has to be communicated to the central catalogue. 
In order to achieve this OAI-PMH identifies the support for deleted records through the *deletedRecord* element retrieved in the Identify request. 
Valid responses are no, persistent and transient. 
SDMS contributing data centres must support *transient* and must maintain transient records for at least 1 month footnote:[This may change.]. 
More information on this feature is available in http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords[OAI-PMH specification of deleted records].
Requirement::
The OAI-PMH interface by default offers metadata in http://dublincore.org/[Dublin Core]. 
This is insufficient for SDMS purposes. 
Metadata has to be offered in https://github.com/ISO-TC211/XML[ISO19115] and/or http://gcmd.nasa.gov/add/difguide/[GCMD DIF]. 

Recommendation::
Details on the discovery metadata specifications are provided below. 
In order to properly identify the metadata standards in the OAI-PMH service endpoint it is recommended to use the keywords below.
Keywords::: 
- “dif” for GCMD DIF, preferably (dif9 or dif10 to reflect the version)
- “iso19139” for the ISO19115 minimum profile

===== OGC CSW

The Open Geospatial Consortium Catalogue Services for the Web (OGC CSW <<RD-14>>) is another standard for exposing the content of a catalogue in a standardised form. 
Similar to OAI-PMH records are exposed using XML. 
Compared to OAI-PMH, OGC CSW is more expensive to implement from the specification although there are several tools supporting it. 
It is the recommended exchange mechanism for metadata within the European framework INSPIREfootnote:[Not required for scientific data.] and is supported by the SIOS Data Access Portal. 

[horizontal]
Requirement:: 
Do not use SOAP.
Requirement::
Serve ISO19115/ISO19139. 
Detailed information on ISO19115 profiles is provided later in the document.

IMPORTANT: Only version 2.0.2 exchange has been thoroughly tested so far.

===== Sensor Description (Not yet supported)

The implementation of Sensor Web Enablement (SWE) as a useful suite of standards of the OGC for building the Sensor Web is recommended to allow for interoperability and to reduce the integration efforts of new data sources, although not supported by the SIOS Data Management System central node yet. 

Recommended data formats are Observations and Measurements (O&M) and SensorML.
For describing devices and sensors in terms of metadata to NRT-data streams or archived and disseminated data basic SensorML should be applicable. 
These are Standard for modelling/encoding sensor Metadata based on XML (latest version: SensorML 2.0). 
Hence Editors are needed to facilitate the provision of these metadata to the SDMS with focus on ISO 19115 metadata. 
As controlled vocabulary for device description the NERC-SeaDataNet vocabulary could be a useful recommendation if agreed on.  

WARNING: SWE is not supported for data discovery purposes, but is considered for other purposes within SIOS.

===== Other

Harvesting of discovery information using OpenSearch being tested, but is yet not supported for regular exchange of discovery metadata within SIOS. 
According to <<RD-24>> OpenSearch is a “collection of simple formats for the sharing of search results. 
The OpenSearch description document format can be used to describe a search engine so that it can be used by search client applications.”

Within the Polar Data Management Community an effort has been addressing exchange of discovery metadata using schema.org.
The intention is to make it easier for data repositories to announce their datasets by embedding schema.org in web pages.
The work is based on ESIP's Science on schema.orgfootnote:[https://github.com/ESIPFed/science-on-schema.org].
Harvesting information from data repositories serving schema.org is under testing for third party data repositories. 

NOTE: More information on schema.org to be added.

==== Information structures for discovery metadata

===== Internal discovery model

SIOS is harvesting discovery metadata from data centres using established discovery metadata schemes and transforms this information into the internal information model used. 
<<discovery-model-elements>> below shows the elements of the information model and mappings against ISO19115 and GCMD DIF.
Further mappings are under development.

include::sdms_iog_ch02-discovery-model-mapping.adoc[]

include::sdms_iog_ch02-discovery-iso19115.adoc[]

include::sdms_iog_ch02-discovery-gcmd.adoc[]

