name: build adocs

on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Asciidoctoring the docs to PDF and HTML
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check that docker-compose is available
      run: which docker-compose

    - name: Build PDF and HTML
      run: docker-compose -f docker-compose-asciidoctor.yml up

    - name: Commit changed files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f doc/sdms_iog.pdf
        git add -f doc/sdms_iog.html
        git commit -m "Automatic updated by GitHub Action"

    - name: push code to ${{ github.ref }}
      run: |
        remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:${{ github.ref }} --follow-tags
